# Codecov configuration for Voidix Web project
# Coverage monitoring strategy: informational rather than blocking

# Global settings
codecov:
  require_ci_to_pass: no

# Coverage status check configuration
coverage:
  status:
    # Project overall coverage
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
        
    # New code coverage (patch)
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true

  # Coverage range configuration
  range: 70..100
  round: down
  precision: 2

# PR comment configuration
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

# Ignore paths configuration
ignore:
  - "src/test/"
  - "scripts/"
  - "**/*.d.ts"
  - "**/*.config.*"
  - "dist/"
  - "coverage/"
  - "node_modules/"