name: Website Check

on:
  pull_request:
    branches: [master]
  merge_group:
  workflow_dispatch:

env:
  NODE_VERSION: '22.12.0'

jobs:
  check:
    name: Astro Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - run: npm ci --prefer-offline --no-audit
      - run: npm run format:check
      - run: npm run check

  build:
    name: Production Build
    runs-on: ubuntu-latest
    needs: check

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - run: npm ci --prefer-offline --no-audit
      - run: npm run build
